Restore sudo

diff --git a/.config/i3/blocks/packages b/.config/i3/blocks/packages
--- a/.config/i3/blocks/packages
+++ b/.config/i3/blocks/packages
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 
 URGENT_VALUE=25
-APT_LIST=$(su - -c "/usr/bin/apt update -qq"  &> /dev/null && apt list --upgradable 2>/dev/null | wc -l)
+APT_LIST=$(sudo apt update -qq  &> /dev/null && apt list --upgradable 2>/dev/null | wc -l)
 PACKAGE_COUNT=$((APT_LIST-1))
 if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
   echo "${PACKAGE_COUNT}" # full-text
@@ -10,4 +10,10 @@ if [[ "${PACKAGE_COUNT}" -gt 0 ]]; then
   if [[ "${PACKAGE_COUNT}" -gt "${URGENT_VALUE}" ]]; then
     exit 33
   fi
+elif [[ -z "$APT_LIST" ]]; then
+  echo "!"
+  echo "error updating packages"
+  echo ""
+  exit 33
 fi
+
